<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="All" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NSubstitute.Analyzers.CSharp" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Apps\CqrsProject.App.GrpcServer\CqrsProject.App.GrpcServer.csproj" />
    <ProjectReference Include="..\..\Commons\CqrsProject.Commons.Test\CqrsProject.Commons.Test.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="..\..\..\src\Apps\CqrsProject.App.GrpcServer\Protos\V1\Me\me_service.proto" GrpcServices="Client" Link="Protos\V1\Me\me_service.proto" />
  </ItemGroup>
</Project>